version: "3.5"

services:
  web:
    image: nginx:1.18-alpine
    container_name: cake4-nginx
    build: ./nginx/
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../app:/var/www/html/app
    networks:
      - frontend
      - backend
    depends_on:
      - app
      - db

  app:
    container_name: cake4-php
    build: ./phpfpm/
    volumes:
      - ../app:/var/www/html/app
      - ./phpfpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
    networks:
      - backend

  db:
    image: mysql:8
    container_name: cake4-mysql
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: cakephp
      MYSQL_DATABASE: cake_cms
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    networks:
      - backend

volumes:
  db-store:
    driver: local

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
